---
  # Per default the socket is owned by nagios:www-run
  - name: Enable icinga modules
    command: icinga2 feature enable {{ item }} creates=/etc/icinga2/features-enabled/{{ item }}.conf
    notify: restart icinga
    with_items:
      - api
      - checker
      - mainlog

  - name: Disable icinga modules
    command: icinga2 feature disable {{ item }} removes=/etc/icinga2/features-enabled/{{ item }}.conf
    notify: restart icinga
    with_items:
      - graphite
      - ido-mysql
      - perfdata
      - notification

  - name: Concat CA and CRL
    assemble: src=/etc/icinga2/pki/ca dest=/etc/icinga2/pki/ca-mag.crt
    changed_when: False

  - name: Create icinga config files
    template: src={{item }}.j2 dest=/etc/icinga2/conf.d/{{item }} owner=root group=root mode=0644
    notify: restart icinga
    with_items:
      - templates.conf

  - name: Create icinga main configs
    template: src={{ item }}.j2 dest=/etc/icinga2/{{ item }} owner=root group=root mode=0644
    notify: restart icinga
    with_items:
      - icinga2.conf
      - constants.conf
      - zones.conf

  - name: Configure icinga features
    template: src={{ item }}.j2 dest=/etc/icinga2/features-available/{{ item }} owner=root group=nagios mode=0640
    notify: restart icinga
    with_items:
      - api.conf
