---
  - name: Load icinga version
    become: True
    shell: "icinga2 -V | sed -E 's/.*version: r([0-9.-]*)-1.*/\\1/g' | head -n1"
    register: icversion
    check_mode: False
    changed_when: False

  - name: Enable icinga modules
    become: True
    command: icinga2 feature enable {{ item }} creates=/etc/icinga2/features-enabled/{{ item }}.conf
    notify: restart icinga
    with_items:
      - api
      - checker
      - mainlog

  - name: Disable icinga modules
    become: True
    command: icinga2 feature disable {{ item }} removes=/etc/icinga2/features-enabled/{{ item }}.conf
    notify: restart icinga
    with_items:
      - graphite
      - ido-mysql
      - perfdata
      - notification

  - name: Create icinga config files
    become: True
    template: src={{item }}.j2 dest=/etc/icinga2/conf.d/{{item }} owner=root group=root mode=0644
    notify: restart icinga
    with_items:
      - templates.conf

  - name: Create icinga main configs
    become: True
    template: src={{ item }}.j2 dest=/etc/icinga2/{{ item }} owner=root group=root mode=0644
    notify: restart icinga
    with_items:
      - icinga2.conf
      - constants.conf
      - zones.conf

  - name: Configure icinga features
    become: True
    template: src={{ item }}.j2 dest=/etc/icinga2/features-available/{{ item }} owner=root group=nagios mode=0640
    notify: restart icinga
    with_items:
      - api.conf

  - name: Ensure icinga2 is stopped
    become: True
    service: name=icinga2 state=stopped
    when: icclean|bool

  - name: Remove icinga2 state
    become: True
    shell: rm -Rf /var/lib/icinga2/api ; rm -f /var/lib/icinga2/icinga2.state ; rm /var/lib/icinga2/modified-attributes.conf ; rm -Rf /var/log/icinga2/*
    when: icclean|bool

  - name: Start icinga2
    become: True
    service: name=icinga2 state=started
    when: icclean|bool
